#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine with task requirements
# (this script will be run on the server itself)

apt-get update
apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
service nginx restart
