#!/usr/bin/env bash
# Bash script that containing commands to automatically configure
# a Ubuntu machine to respect these requirements:
# Configure your Nginx server so that /redirect_me redirects to another page.
# The redirection must be a “301 Moved Permanently”

apt-get update
apt-get -y install nginx
sed -ie "s/^server {$/server {\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/g" /etc/nginx/sites-available/default
service nginx restart
