#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
# Requirements:
# The page must return an HTTP 404 error code
# The page must contain the string Ceci n'est pas une page
# Using what you did with 3-redirection, write 4-not_found_page_404 so that it configures a brand new Ubuntu machine to the requirements asked in this task

apt-get update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
touch /usr/share/nginx/html/my_404.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/my_404.html
sed -ie "s/^\tserver_name _;$/\tserver {\n\terror_page 404 \/my_404.html;\n\t\tlocation = \/my_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/g" /usr/share/nginx/html/my_404.html
service nginx restart
