#!/usr/bin/env bash
# script that configures a brand new Ubuntu machine to the
# requirements asked in this task
# (Configure Nginx so that its HTTP response contains a custom header
# (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By)

apt-get update
apt-get -y install nginx
sed -ie "s/^server {$/server {\n\tadd_header X-Served-By $HOSTNAME;/g" /etc/nginx/sites-available/default
service nginx restart
