#!/usr/bin/env bash
# bash script that generates a MySQL dump and creates a compressed archive out of it

mysqldump -u root -p"$1" --all-databases > backup.sql
mydate=$(date +"%d-%m-%Y")
sudo tar -cvzf "$mydate".tar.gz backup.sql
