#!/usr/bin/env bash
# This bash script
# 1. Creates the file /var/run/holbertonscript.pid containing its PID
# 2. Displays "To infinity and beyond" indefinitely
# 3. Displays "I hate the kill command" when receiving a SIGTERM signal
# 4. Displays "Y U no love me?!" when receiving a SIGINT signal
# 5. Deletes the file /var/run/holbertonscript.pid and terminates...
# ...itself when receiving a SIGQUIT or SIGTERM signal

su echo $$ > /var/run/holbertonscript.pid
trap "echo 'I hate the kill command'; rm /var/run/holbertonscript.pid; exit" SIGTERM
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
