#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd...
# ...using the while loop + IFS
# format given in task

file="/etc/passwd"
while IFS=':' read -r -a line
do
    echo "The user ${line[0]} is part of the ${line[3]} gang, lives in ${line[5]} and rides ${line[6]}. ${line[2]}'s place is protected by the passcode ${line[1]}, more info about the user here: ${line[4]}"
done < "$file"



# another way:
#
# file="/etc/passwd"
# while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
# do
#    echo "The user $f1 is part of the $f4 gang, lives in $f6 and rides $f7. $f3's place is protected by the passcode $f2, more info about the user here: $f5"
# done < $file
