#!/usr/bin/env bash
# This script that displays the visitor IP along with the HTTP status code...
# ...from the Apache log file
# Format: IP HTTP_CODE
# required to use awk

awk '{print $1 " " $9}' apache-access.log
