#!/usr/bin/env bash
# Building on the previous exercise, this script groups visitors...
# ...by IP and HTTP status code, and displays this data
# format must be: OCCURENCE_NUMBER IP HTTP_CODE
# Ordered from the greatest to the lowest number of occurrences
# required to use awk

awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -nr
