#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times using a while loop
# on the 9th iteration, it displays "Hi" after "Holberton School"

count=1
while [ $count -le 10 ]
do
    echo Holberton School
    if [ $count -eq 9 ]
    then
        echo Hi
    fi
    ((count++))
done
