#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes
# displays hours from 0 to 12 and displays minutes from 1 to 59

countmin=1
counthr=0
while [ $counthr -le 12 ]
do
    echo Hour: $counthr
    while [ $countmin -le 59 ]
    do
        echo $countmin
        ((countmin++))
    done
    countmin=1
    ((counthr++))
done
