#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/my_hosts_test
sed -i s/127.0.0.1/127.0.0.2/ ~/my_hosts_test
echo "8.8.8.8 facebook.com" >> ~/my_hosts_test
cp -f ~/my_hosts_test /etc/hosts
