#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

grep -vwE "(localhost|facebook.com)" /etc/hosts > ~/my_hosts_test
echo "127.0.0.2         localhost" >> ~/my_hosts_test
echo "8.8.8.8        facebook.com" >> ~/my_hosts_test
cp -f ~/my_hosts_test /etc/hosts
