#!/usr/bin/env bash

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -ie "1 i user nginx;" /etc/nginx/nginx.conf
sudo service nginx restart

# sudo su -c sed -ie "1 i user nginx;" /etc/nginx/nginx.conf /bin/sh root
