#!/usr/bin/env bash
# Bash script that creates an RSA key pair.
# Name of the created private key must be holberton
# Number of bits in the created key to be created 4096
# The created key must be protected by the passphrase betty

ssh-keygen -f holberton -N betty -b 4096

# -f: specifies filename of the key file
# -b: number of bits in the key to create
# -N: new passphrase
